summary: XML-based font configuration tools
web-url: https://wiki.freedesktop.org/www/Software/fontconfig
git-url: https://gitlab.freedesktop.org/fontconfig/fontconfig
src-url: https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.15.0.tar.xz
src-sha: 63a0658d0e06e0fa886106452b58ef04f21f58202ea02a94c39de0d3335d7c0e
license: MIT
dep-pkg: gettext libiconv libexpat json-c util-linux freetype2-with-harfbuzz
dep-upp: gperf
install: |
    configure \
        --enable-iconv \
        --disable-docs \
        --with-libiconv-prefix="$libiconv_INSTALL_DIR" \
        --with-libintl-prefix="$gettext_INSTALL_DIR" \
        --with-expat="$libexpat_INSTALL_DIR"
