summary: GSettings schemas for desktop components
web-url: https://download.gnome.org/sources/gsettings-desktop-schemas/
src-url: https://download.gnome.org/sources/gsettings-desktop-schemas/44/gsettings-desktop-schemas-44.0.tar.xz
src-sha: eb2de45cad905994849e642a623adeb75d41b21b0626d40d2a07b8ea281fec0e
license: LGPL-2.1-or-later
dep-pkg: glib gobject-introspection expat
bsystem: meson
