summary: GSettings schemas for desktop components
web-url: https://download.gnome.org/sources/gsettings-desktop-schemas/
src-url: https://download.gnome.org/sources/gsettings-desktop-schemas/43/gsettings-desktop-schemas-43.0.tar.xz
src-sha: 5d5568282ab38b95759d425401f7476e56f8cbf2629885587439f43bd0b84bbe
license: LGPL-2.1-or-later
dep-pkg: glib gobject-introspection expat
bsystem: meson
