summary: GSettings schemas for desktop components
web-url: https://download.gnome.org/sources/gsettings-desktop-schemas/
src-url: https://download.gnome.org/sources/gsettings-desktop-schemas/45/gsettings-desktop-schemas-45.0.tar.xz
src-sha: 365c8d04daf79b38c8b3dc9626349a024f9e4befdd31fede74b42f7a9fbe0ae2
license: LGPL-2.1-or-later
dep-pkg: glib gobject-introspection expat
bsystem: meson
