name: workflow1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        tag: [22.04]
        pkg: [aalib,ag,age,alacritty,alass,algernon,anchor-cli,antibody,apkeep,aptly,archiver,args,aria2,async++,atuin,automake,autossh,autotools-setup,axel,b3sum,bandwhich,base16,base64,bash,basis_universal,bat,bazelisk,bc,bcrypt,bear,bgrep,binaryen,bind,binocle,bison,bitcoin,bk,bmake,botan,bottom,boxes,brook,broot,bsdtar,bullet,byacc,caddy,cargo-c,cargo-deb,catch2]
        flavor: [c]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - run: apt -y update
        - run: apt -y install curl xz-utils g++ gfortran linux-headers-generic

        - uses: actions/checkout@v3

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.1-linux-x86_64.tar.xz
            tar vxf ppkg-*-linux-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg formula-repo-init test https://github.com/leleliu008/ppkg-formula-repository-official-core
        - run: mv formula ~/.ppkg/repos.d/test/
        - run: ./ppkg install ${{ matrix.pkg }} --link-type=static-full

  alpine:
    if: ${{ true }}
    strategy:
      fail-fast: false
      matrix:
        tag: [3.17]
        pkg: [aalib,ag,age,alacritty,alass,algernon,anchor-cli,antibody,apkeep,aptly,archiver,args,aria2,async++,atuin,automake,autossh,autotools-setup,axel,b3sum,bandwhich,base16,base64,bash,basis_universal,bat,bazelisk,bc,bcrypt,bear,bgrep,binaryen,bind,binocle,bison,bitcoin,bk,bmake,botan,bottom,boxes,brook,broot,bsdtar,bullet,byacc,caddy,cargo-c,cargo-deb,catch2]
        flavor: [c]

    runs-on:   ubuntu-latest
    container: alpine:${{ matrix.tag }}

    steps:
        - run: apk update
        - run: apk add curl g++ gfortran libc-dev linux-headers

        - uses: actions/checkout@v3

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.1-linux-x86_64.tar.xz
            tar vxf ppkg-*-linux-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg formula-repo-init test https://github.com/leleliu008/ppkg-formula-repository-official-core
        - run: mv formula/* ~/.ppkg/repos.d/test/formula/
        - run: ./ppkg install ${{ matrix.pkg }} --link-type=static-full


  macos:
    if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        tag: [12]
        pkg: [aalib,ag,age,alacritty,alass,algernon,anchor-cli,antibody,apkeep,aptly,archiver,args,aria2,async++,atuin,automake,autossh,autotools-setup,axel,b3sum,bandwhich,base16,base64,bash,basis_universal,bat,bazelisk,bc,bcrypt,bear,bgrep,binaryen,bind,binocle,bison,bitcoin,bk,bmake,botan,bottom,boxes,brook,broot,bsdtar,bullet,byacc,caddy,cargo-c,cargo-deb,catch2]
        flavor: [sh, c]

    runs-on: macos-${{ matrix.tag }}

    steps:
        - run: brew update
        - run: brew install --overwrite python@3.10 python@3.11

        - uses: actions/checkout@v3

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.1-macos-x86_64.tar.xz
            tar vxf ppkg-*-macos-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg formula-repo-init test https://github.com/leleliu008/ppkg-formula-repository-official-core
        - run: mv formula ~/.ppkg/repos.d/test/
        - run: ./ppkg install ${{ matrix.pkg }} --link-type=static-most
