name: workflow1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        tag: [18.04, 20.04, 22.04]
        pkg: [acl,age,algernon,anchor-cli,antibody,aptly,archiver,aria2,axel,b3sum,bandwhich,base64,bat,bc,bcrypt,bear,berkeley-db,bind,binocle,bison,bk,blake3,bottom,brook,broot,c-examples,caddy,cargo-c,ccache,cflow,cheat]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository
            path: ppkg-formula-repository

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository /opt/ppkg/repos.d/offical

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg

        - run: bin/ppkg env

        - run: apt -y update
        - run: apt -y install curl g++ gfortran linux-headers-generic

        - run: bin/ppkg setup

        - run: bin/ppkg install ${{ matrix.pkg }}
