name: workflow12

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  alpine:
    if: true

    strategy:
      fail-fast: false
      matrix:
        tag: [3.19]
        pkg: [runc,rust-analyzer,rustscan,rustup-init,ruy,samurai,scc,sccache,sd,shc,shell2http,shellcheck,shellharden,shiori,silicon,simplex-chat,six,sjpeg,skcms,sl,slirp4netns,sndfile,socat,soundtouch,speex,spirv-headers,sq,sqlite3,sqlite3_analyzer,squashfs,squashfuse,srs,srt,sshfs,starship,stow,strace,stwolame,stylua,subfinder,superfile,supervisord,suricata,svn-lite,svt-av1,swig,syncthing,sysdig,sysinfo,szip,tarlz,tbls,tbox,tcc,tcl-core,tcpdump,tdu,tealdeer,tectonic,tengo]
        flavor: [sh]

    runs-on:   ubuntu-latest
    container: alpine:${{ matrix.tag }}

    steps:
        - run: apk update
        - run: apk add curl g++ gfortran libc-dev linux-headers

        - uses: actions/checkout@v4

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/${{ github.ref_name }}/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.2-linux-x86_64.tar.xz
            tar vxf ppkg-*-linux-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg about
        - run: ./ppkg install ${{ matrix.pkg }} --static -I formula/linux -I formula


  ubuntu:
    if: true

    strategy:
      fail-fast: false
      matrix:
        tag: [24.04]
        pkg: [runc,rust-analyzer,rustscan,rustup-init,ruy,samurai,scc,sccache,sd,shc,shell2http,shellcheck,shellharden,shiori,silicon,simplex-chat,six,sjpeg,skcms,sl,slirp4netns,sndfile,socat,soundtouch,speex,spirv-headers,sq,sqlite3,sqlite3_analyzer,squashfs,squashfuse,srs,srt,sshfs,starship,stow,strace,stwolame,stylua,subfinder,superfile,supervisord,suricata,svn-lite,svt-av1,swig,syncthing,sysdig,sysinfo,szip,tarlz,tbls,tbox,tcc,tcl-core,tcpdump,tdu,tealdeer,tectonic,tengo]
        flavor: [sh]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - run: apt -y update
        - run: apt -y install curl xz-utils g++ gfortran linux-headers-generic

        - uses: actions/checkout@v4

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/${{ github.ref_name }}/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.2-linux-x86_64.tar.xz
            tar vxf ppkg-*-linux-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg about
        - run: ./ppkg install ${{ matrix.pkg }} -I formula/linux -I formula


  macos:
    if: false

    strategy:
      fail-fast: false
      matrix:
        tag: [14]
        pkg: [runc,rust-analyzer,rustscan,rustup-init,ruy,samurai,scc,sccache,sd,shc,shell2http,shellcheck,shellharden,shiori,silicon,simplex-chat,six,sjpeg,skcms,sl,slirp4netns,sndfile,socat,soundtouch,speex,spirv-headers,sq,sqlite3,sqlite3_analyzer,squashfs,squashfuse,srs,srt,sshfs,starship,stow,strace,stwolame,stylua,subfinder,superfile,supervisord,suricata,svn-lite,svt-av1,swig,syncthing,sysdig,sysinfo,szip,tarlz,tbls,tbox,tcc,tcl-core,tcpdump,tdu,tealdeer,tectonic,tengo]
        flavor: [sh]

    runs-on: macos-${{ matrix.tag }}

    steps:
        - uses: actions/checkout@v4

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/${{ github.ref_name }}/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.2-macos-14.0-arm64.tar.xz
            tar vxf ppkg-0.1000.2-macos-14.0-arm64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg about
        - run: ./ppkg install ${{ matrix.pkg }} -I formula/macos -I formula
