name: workflow12

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        tag: [18.04, 20.04, 22.04]
        pkg: [openfst,openlibm,openmpi,p7zip,packcc,patch,patchelf,pget,physfs,pigz,pkg-config,pkgconf,plog,pngquant,poco,procps,procs,progress,proj,proot,pup,putty,pybind11]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository
            path: ppkg-formula-repository

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository /opt/ppkg/repos.d/offical

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg

        - run: bin/ppkg env

        - run: apt -y update
        - run: apt -y install curl xz-utils g++ gfortran linux-headers-generic

        - run: bin/ppkg setup

        - run: bin/ppkg install ${{ matrix.pkg }}
