name: workflow13

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        tag: [18.04, 20.04, 22.04]
        pkg: [rapidjson,rclone,re2c,redis,restic,rhash,ripgrep,rlwrap,rsass,rsync,rtmpdump,rtorrent,rust-analyzer,sassc,scc,sccache,sd,shc,shell2http,shiori,silicon,sl,soundtouch,srs,starship,strace,stylua,supervisord,suricata,svn-lite]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository
            path: ppkg-formula-repository

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository /opt/ppkg/repos.d/offical

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg

        - run: bin/ppkg env

        - run: apt -y update
        - run: apt -y install curl g++ gfortran linux-headers-generic

        - run: bin/ppkg setup

        - run: bin/ppkg install ${{ matrix.pkg }}
