name: workflow16

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    if: ${{ true }}
    strategy:
      fail-fast: false
      matrix:
        tag: [20.04, 22.04]
        pkg: [rust-analyzer,sassc,scc,sccache,sd,shaderc,shc,shell2http,shiori,silicon,sl,socat,soundtouch,spirv-tools,srs,starship,strace,stylua,supervisord,suricata,svn-lite,syncthing,systemd,szip]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository-offical-core
            path: ppkg-formula-repository-offical-core

        - run: apt -y update
        - run: apt -y install curl xz-utils g++ gfortran linux-headers-generic

        - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
        - run: chmod a+x ppkg

        - run: ./ppkg setup

        - run: ./ppkg env

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository-offical-core /opt/ppkg/repos.d/offical-core

        - run: ./ppkg install ${{ matrix.pkg }}

  macos:
    if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        tag: [12]
        pkg: [rust-analyzer,sassc,scc,sccache,sd,shaderc,shc,shell2http,shiori,silicon,sl,socat,soundtouch,spirv-tools,srs,starship,strace,stylua,supervisord,suricata,svn-lite,syncthing,systemd,szip]

    runs-on: macos-${{ matrix.tag }}

    env:
        ACLOCAL_PATH: /usr/local/share/aclocal

    steps:
        - run: brew uninstall go@1.17

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository-offical-core
            path: ppkg-formula-repository-offical-core

        - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
        - run: chmod a+x ppkg

        - run: ./ppkg setup --use-system-package-manager

        - run: ./ppkg env

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository-offical-core /opt/ppkg/repos.d/offical-core

        - run: ./ppkg install ${{ matrix.pkg }}
