name: workflow2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        tag: [18.04, 20.04, 22.04]
        pkg: [cheat,check,chezmoi,chicken,choose,cjson,clash,cmake,cpio,cppcheck,cpu_features,croc,crosstool-ng,crowbook,ctop,cue,curlie,darkhttpd,dasel,dash,delta,diffutils,distcc,dmalloc,dog,dos2unix,dua,duf,dufs,dust,ed,elvish,epsilon,esbuild,ethereum,eudev]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository
            path: ppkg-formula-repository

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository /opt/ppkg/repos.d/offical

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg

        - run: bin/ppkg env

        - run: apt -y update
        - run: apt -y install curl g++ gfortran linux-headers-generic

        - run: bin/ppkg setup

        - run: bin/ppkg install ${{ matrix.pkg }}
