name: workflow2

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  alpine:
    if: false

    strategy:
      fail-fast: false
      matrix:
        tag: [3.19]
        pkg: [cxxopts,d2,darkhttpd,dasel,dash,dav1d,delta,difftastic,diffutils,distcc,dmalloc,dns2tcp,dnslookup,dnsmap,dnsx,dog,doggo,dolt,dos2unix,dot_static,doxygen,dpkg,dtc,dua,duf,dufs,duktape,dust,e2fsprogs,easyutils,ed,effcee,eget,elfcat,elfutils,elvish,epsilon,erdtree,esbuild,ethereum,eudev,exa,exhale,exiv2,eza,fakeroot,fcp,fd,fdroidcl,fff,ffmpeg,fftw,figlet,file,findent,findutils,fish,flac,flatbuffers,flatc,flex,flock,fnm,fortune,frei0r,fselect,fsmon,fswatch,fuse-overlayfs,fzf,fzy,g,garble,gat,gawk,gbt,gcc,gcc@12,gdb,gdbm,gdk-pixbuf-tools,gdu,geographiclib,germanium,getopt,gettext-tools,gf,gh,ghcup,ghr,gif2png,giflib,gindent,git,git-cliff,git-lfs,gitoxide,gitui,gitwatch,glew,glib-tools,glib-tools@2.78,glib@2.78,glow,glslviewer,glyr,gmake,gn,gnu-barcode,gnu-which,gnupg,gnuplot,gnutls,go-md2man,go-tools,gobject-introspection@1.76,gobject-introspection@1.78,godu,gogs,golang]
        flavor: [sh]

    runs-on:   ubuntu-latest
    container: alpine:${{ matrix.tag }}

    steps:
        - run: apk update
        - run: apk add curl g++ gfortran libc-dev linux-headers

        - uses: actions/checkout@v4

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/${{ github.ref_name }}/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.2-linux-x86_64.tar.xz
            tar vxf ppkg-*-linux-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg about
        - run: ./ppkg install ${{ matrix.pkg }} --static -I formula/linux -I formula


  ubuntu:
    if: true

    strategy:
      fail-fast: false
      matrix:
        tag: [24.04]
        pkg: [cxxopts,d2,darkhttpd,dasel,dash,dav1d,delta,difftastic,diffutils,distcc,dmalloc,dns2tcp,dnslookup,dnsmap,dnsx,dog,doggo,dolt,dos2unix,dot_static,doxygen,dpkg,dtc,dua,duf,dufs,duktape,dust,e2fsprogs,easyutils,ed,effcee,eget,elfcat,elfutils,elvish,epsilon,erdtree,esbuild,ethereum,eudev,exa,exhale,exiv2,eza,fakeroot,fcp,fd,fdroidcl,fff,ffmpeg,fftw,figlet,file,findent,findutils,fish,flac,flatbuffers,flatc,flex,flock,fnm,fortune,frei0r,fselect,fsmon,fswatch,fuse-overlayfs,fzf,fzy,g,garble,gat,gawk,gbt,gcc,gcc@12,gdb,gdbm,gdk-pixbuf-tools,gdu,geographiclib,germanium,getopt,gettext-tools,gf,gh,ghcup,ghr,gif2png,giflib,gindent,git,git-cliff,git-lfs,gitoxide,gitui,gitwatch,glew,glib-tools,glib-tools@2.78,glib@2.78,glow,glslviewer,glyr,gmake,gn,gnu-barcode,gnu-which,gnupg,gnuplot,gnutls,go-md2man,go-tools,gobject-introspection@1.76,gobject-introspection@1.78,godu,gogs,golang]
        flavor: [sh]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - run: apt -y update
        - run: apt -y install curl xz-utils g++ gfortran linux-headers-generic

        - uses: actions/checkout@v4

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/${{ github.ref_name }}/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.2-linux-x86_64.tar.xz
            tar vxf ppkg-*-linux-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg about
        - run: ./ppkg install ${{ matrix.pkg }} -I formula/linux -I formula


  macos:
    if: false

    strategy:
      fail-fast: false
      matrix:
        tag: [14]
        pkg: [cxxopts,d2,darkhttpd,dasel,dash,dav1d,delta,difftastic,diffutils,distcc,dmalloc,dns2tcp,dnslookup,dnsmap,dnsx,dog,doggo,dolt,dos2unix,dot_static,doxygen,dpkg,dtc,dua,duf,dufs,duktape,dust,e2fsprogs,easyutils,ed,effcee,eget,elfcat,elfutils,elvish,epsilon,erdtree,esbuild,ethereum,eudev,exa,exhale,exiv2,eza,fakeroot,fcp,fd,fdroidcl,fff,ffmpeg,fftw,figlet,file,findent,findutils,fish,flac,flatbuffers,flatc,flex,flock,fnm,fortune,frei0r,fselect,fsmon,fswatch,fuse-overlayfs,fzf,fzy,g,garble,gat,gawk,gbt,gcc,gcc@12,gdb,gdbm,gdk-pixbuf-tools,gdu,geographiclib,germanium,getopt,gettext-tools,gf,gh,ghcup,ghr,gif2png,giflib,gindent,git,git-cliff,git-lfs,gitoxide,gitui,gitwatch,glew,glib-tools,glib-tools@2.78,glib@2.78,glow,glslviewer,glyr,gmake,gn,gnu-barcode,gnu-which,gnupg,gnuplot,gnutls,go-md2man,go-tools,gobject-introspection@1.76,gobject-introspection@1.78,godu,gogs,golang]
        flavor: [sh]

    runs-on: macos-${{ matrix.tag }}

    steps:
        - uses: actions/checkout@v4

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/${{ github.ref_name }}/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.2-macos-14.0-arm64.tar.xz
            tar vxf ppkg-0.1000.2-macos-14.0-arm64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg about
        - run: ./ppkg install ${{ matrix.pkg }} -I formula/macos -I formula
