name: workflow2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    if: ${{ true }}
    strategy:
      fail-fast: false
      matrix:
        tag: [20.04, 22.04]
        pkg: [catimg,ccache,cdrtools,cereal,c-examples,cfitsio,cflow,cgif,chafa,cheat,check,chezmoi,chicken,choose,circleci-cli,clash,cli11,cmake,coreutils,cpio,cppcheck,cppunit,cpu_features,cpuinfo,croc,crosstool-ng,crowbook,ctop,cue,curlie,cxxopts,d2,darkhttpd,dasel,dash,delta,diffutils,distcc,dmalloc,dns2tcp,dnsmap,dog,doggo,dos2unix,doxygen,dua,duf,dufs,dust,e2fsprogs]
        flavor: [sh, c]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - run: apt -y update
        - run: apt -y install curl xz-utils g++ gfortran linux-headers-generic

        - uses: actions/checkout@v3

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.0-linux-x86_64.tar.xz
            tar vxf ppkg-*-linux-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg formula-repo-init test https://github.com/leleliu008/ppkg-formula-repository-offical-core
        - run: mv formula ~/.ppkg/repos.d/test/
        - run: ./ppkg install ${{ matrix.pkg }}

  macos:
    if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        tag: [12]
        pkg: [catimg,ccache,cdrtools,cereal,c-examples,cfitsio,cflow,cgif,chafa,cheat,check,chezmoi,chicken,choose,circleci-cli,clash,cli11,cmake,coreutils,cpio,cppcheck,cppunit,cpu_features,cpuinfo,croc,crosstool-ng,crowbook,ctop,cue,curlie,cxxopts,d2,darkhttpd,dasel,dash,delta,diffutils,distcc,dmalloc,dns2tcp,dnsmap,dog,doggo,dos2unix,doxygen,dua,duf,dufs,dust,e2fsprogs]
        flavor: [sh, c]

    runs-on: macos-${{ matrix.tag }}

    steps:
        - run: brew update
        - run: brew install --overwrite python@3.10 python@3.11

        - uses: actions/checkout@v3

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/ppkg-0.1000.0-macos-x86_64.tar.xz
            tar vxf ppkg-*-macos-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg formula-repo-init test https://github.com/leleliu008/ppkg-formula-repository-offical-core
        - run: mv formula ~/.ppkg/repos.d/test/
        - run: ./ppkg install ${{ matrix.pkg }}
