name: workflow4

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    if: ${{ true }}
    strategy:
      fail-fast: false
      matrix:
        tag: [20.04, 22.04]
        pkg: [e2fsprogs,ed,eigen,elvish,epsilon,esbuild,ethereum,eudev,exa,exhale,fakeroot,fcp,fd,fdroidcl,fff,figlet,findutils,fish,flatbuffers,flex,fortune]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - run: apt -y update
        - run: apt -y install curl xz-utils g++ gfortran linux-headers-generic

        - uses: actions/checkout@v3

        - run: install -d ~/.ppkg/repos.d/offical-core/
        - run: mv formula ~/.ppkg/repos.d/offical-core/
        - run: |
            cat > ~/.ppkg/repos.d/offical-core/.ppkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-offical-core
            branch: master
            pinned: yes
            enabled: yes
            timestamp-added: $(date +%s)
            EOF

        - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
        - run: chmod a+x ppkg
        - run: ./ppkg setup
        - run: ./ppkg env
        - run: ./ppkg install ${{ matrix.pkg }}

  macos:
    if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        tag: [12]
        pkg: [e2fsprogs,ed,eigen,elvish,epsilon,esbuild,ethereum,eudev,exa,exhale,fakeroot,fcp,fd,fdroidcl,fff,figlet,findutils,fish,flatbuffers,flex,fortune]

    runs-on: macos-${{ matrix.tag }}

    steps:
        - run: brew update
        - run: brew uninstall go@1.17
        - run: brew install --overwrite python@3.10 python@3.11

        - uses: actions/checkout@v3

        - run: install -d ~/.ppkg/repos.d/offical-core/
        - run: mv formula ~/.ppkg/repos.d/offical-core/
        - run: |
            cat > ~/.ppkg/repos.d/offical-core/.ppkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-offical-core
            branch: master
            pinned: yes
            enabled: yes
            timestamp-added: $(date +%s)
            EOF

        - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
        - run: chmod a+x ppkg
        - run: ./ppkg setup
        - run: ./ppkg env
        - run: ./ppkg install ${{ matrix.pkg }}
