name: workflow5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        tag: [18.04, 20.04, 22.04]
        pkg: [jsoncpp,jump,kcptun,lazygit,ldns,less,lf,libao,libass,libatomic_ops,libb2,libbcrypt,libcaca,libcap-ng,libcbor,libcddb,libcdio,libcroco,libcrypt,libexecinfo,libexif,libglob,libical,libidn]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository
            path: ppkg-formula-repository

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository /opt/ppkg/repos.d/offical

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg

        - run: bin/ppkg env

        - run: apt -y update
        - run: apt -y install curl

        - run: bin/ppkg setup

        - run: bin/ppkg install ${{ matrix.pkg }}
