name: workflow7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    if: ${{ true }}
    strategy:
      fail-fast: false
      matrix:
        tag: [20.04, 22.04]
        pkg: [miniz,minizip-ng,mkcert,mkcue,mksh,mm-wiki,mold,moreutils,mosh,mozjpeg,mpdecimal,mpg123,mpir,mpv,msgpack-c,mupdf,nano,nanomsg,nasm,navi,ncdu,neofetch,nghttp2,nginx,ngtcp2,ninja,nng,nnn,nsh,ntbtls,nushell,oat++,obfs4proxy,onefetch,open264,openal-soft,openblas,opencolorio,openfst,openlibm,openmpi,openslide,p7zip,packcc,patch,patchelf,pax,pcre2,pget,physfs]
        flavor: [sh, c]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - run: apt -y update
        - run: apt -y install curl xz-utils g++ gfortran linux-headers-generic

        - uses: actions/checkout@v3

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.07/ppkg-0.20.0-linux-x86_64.tar.xz
            tar vxf ppkg-*-linux-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg formula-repo-init test https://github.com/leleliu008/ppkg-formula-repository-offical-core
        - run: mv formula ~/.ppkg/repos.d/test/
        - run: ./ppkg install ${{ matrix.pkg }}

  macos:
    if: ${{ false }}
    strategy:
      fail-fast: false
      matrix:
        tag: [12]
        pkg: [miniz,minizip-ng,mkcert,mkcue,mksh,mm-wiki,mold,moreutils,mosh,mozjpeg,mpdecimal,mpg123,mpir,mpv,msgpack-c,mupdf,nano,nanomsg,nasm,navi,ncdu,neofetch,nghttp2,nginx,ngtcp2,ninja,nng,nnn,nsh,ntbtls,nushell,oat++,obfs4proxy,onefetch,open264,openal-soft,openblas,opencolorio,openfst,openlibm,openmpi,openslide,p7zip,packcc,patch,patchelf,pax,pcre2,pget,physfs]
        flavor: [sh, c]

    runs-on: macos-${{ matrix.tag }}

    steps:
        - run: brew update
        - run: brew install --overwrite python@3.10 python@3.11

        - uses: actions/checkout@v3

        - if: matrix.flavor == 'sh'
          run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg && chmod a+x ppkg

        - if: matrix.flavor == 'c'
          run: |
            curl -LO https://github.com/leleliu008/test/releases/download/2023.10.07/ppkg-0.20.0-macos-x86_64.tar.xz
            tar vxf ppkg-*-macos-x86_64.tar.xz --strip-components=1
            mv bin/ppkg .

        - run: ./ppkg setup
        - run: ./ppkg formula-repo-init test https://github.com/leleliu008/ppkg-formula-repository-offical-core
        - run: mv formula ~/.ppkg/repos.d/test/
        - run: ./ppkg install ${{ matrix.pkg }}
