name: workflow8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        tag: [18.04, 20.04, 22.04]
        pkg: [neofetch,nginx,ngtcp2,ninja,nsh,ntbtls,numactl,nushell,obfs4proxy,openblas,openlibm,openmpi,p7zip,packcc,pango,patch,patchelf,pget,pkg-config,pkgconf,pngquant,procs,progress,proot]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository
            path: ppkg-formula-repository

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository /opt/ppkg/repos.d/offical

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg

        - run: bin/ppkg env

        - run: bin/ppkg setup

        - run: bin/ppkg install ${{ matrix.pkg }}
