name: workflow8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
        os: [ubuntu-22.04]
        pkg: [ntbtls,numactl,nushell,obfs4proxy,openblas,openlibm,openmpi,packcc,pango,patch,patchelf,pget,pkg-config,pkgconf,pngquant,procs,progress,proot,pup,putty,qpdf,quiche,quickjs,rclone,redis]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository
            path: ppkg-formula-repository

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository /opt/ppkg/repos.d/offical

        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg

        - run: bin/ppkg env

        - run: bin/ppkg setup

        - run: bin/ppkg install ${{ matrix.pkg }}
