name: workflow8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        tag: [18.04, 20.04, 22.04]
        pkg: [hydroxide,hyperfine,ideviceinstaller,imagemagick,itstool,ixwebsocket,jemalloc,jfrog-cli,jpeg,jq,json-glib,jsoncpp,jump,kcp,kcptun,lazygit,lcov]

    runs-on:   ubuntu-latest
    container: ubuntu:${{ matrix.tag }}

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository-offical-core
            path: ppkg-formula-repository-offical-core

        - run: apt -y update
        - run: apt -y install curl xz-utils g++ gfortran linux-headers-generic

        - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
        - run: chmod a+x ppkg

        - run: ./ppkg env

        - run: ./ppkg setup

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository-offical-core /opt/ppkg/repos.d/offical-core

        - run: ./ppkg install ${{ matrix.pkg }}

  macos:
    strategy:
      fail-fast: false
      matrix:
        tag: [12, 11]
        pkg: [hydroxide,hyperfine,ideviceinstaller,imagemagick,itstool,ixwebsocket,jemalloc,jfrog-cli,jpeg,jq,json-glib,jsoncpp,jump,kcp,kcptun,lazygit,lcov]

    runs-on: macos-${{ matrix.tag }}

    env:
        ACLOCAL_PATH: /usr/local/share/aclocal

    steps:
        - uses: actions/checkout@v3
          with:
            repository: leleliu008/ppkg-formula-repository-offical-core
            path: ppkg-formula-repository-offical-core

        - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/bin/ppkg
        - run: chmod a+x ppkg

        - run: ./ppkg env

        - run: ./ppkg setup --use-system-package-manager

        - run: install -d /opt/ppkg/repos.d
        - run: mv ppkg-formula-repository-offical-core /opt/ppkg/repos.d/offical-core

        - run: ./ppkg install ${{ matrix.pkg }}
